version: "3.8"

services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: myapp1
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./api
      dockerfile: Dockerfile
    restart: on-failure
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/myapp1
      ALLOWED_HOSTS: localhost, 127.0.0.1
      PORT: 4000
      FRONTEND_URL: http://localhost:5173 
    ports:
      - "4000:4000"
    depends_on:
      - db

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    restart: on-failure
    environment:
      VITE_API_URL: http://localhost:4000
    ports:
      - "5173:5173"   
    depends_on:
      - backend

volumes:
  db-data: